### ISSUE TITLE
Issue downloading packages

### ISSUE THREAD

**Issue by hduqeh** [brittAnderson/psych363Practice#116]
Hello Professor Anderson,

I have been having trouble the past couple of days trying to figure out why I cannot download the packages that are required to get Elpy installed to have Python working efficiently for my project. I thought maybe I missed a step. Could I please get your help?

Kind regards,

Hayaa Duqeh

**Comment by brittAnderson** [comment]
Yes. But to be able to help I need more specifics on your problem. How,
specifically, are you trying to download? What are the error messages or
other problems your are seeing? Are you asking for email help or to
schedule an online meeting. The more specific and concrete the questions
the more targeted and useful the help can be.

Let me know how you wish to proceed.

**Comment by hduqeh** [comment]
Forgive me I've been so confused I have been translating my messages that way too. I traced back my steps to find out why I was having trouble with python on emacs so I went back to the emacs file. I've made my init.el file and copied over the melpa link. I then closed the file and started it up again. I went to list packages but I cannot find use packages and I can't see which packages are coming from Melpa.

Also, I would really appreciate an online meeting with you so I can get back on track. I don't know how I missed a step like this.

Kind regards,

Hayaa Duqeh


Sent from my Bell Samsung device over Canada's largest network.
________________________________

**Comment by brittAnderson** [comment]
What is your flexibility tomorrow afternoon? I have sometime between 3
and 5 pm. Will check back in AM for your response. 

P.S. I don't know if you have been collaborating with classmates, but
if so, and you know they have some problems too invite them to join us -
just let me know the emails so I can include them on the Teams
invitation. You will probably want to have your computer running so you
can test things. Teams does have an android version so you could use
your phone for the video chat and your computer in linux mode to test
our fixes.

**Comment by brittAnderson** [comment]
PS. Probably we ought to just connect by direct email rather than through the issues at this point. Will close this and you can follow up with a direct email.

**Comment by hduqeh** [comment]
May I schedule a meeting with you at 4:30pm? And yes, I'll ask my classmates if they are having a similar issue so they can join in on the conversation too!

Thank you Dr. Anderson
________________________________
