### ISSUE TITLE
Error for loop assignment

### ISSUE THREAD

**Issue by hduqeh** [brittAnderson/psych363Practice#121]
Hello Professor Anderson,

I have finally got things working in terms of packages on emacs. However, when I write my code for python it gives me an error message in the buffer. It says: eldoc error: (error Cannot find executable 'python' , please set ' elpy-rpc-python-command' to an existing executable.)
I'm not sure what this means exactly. Could I please get your help on this?

Also, when updating packages I see on my buffer it says I have 4 packages that need updating but how do I know which ones I'm suppose to update to insert a 'u' and then 'x' ?

**Comment by brittAnderson** [comment]
Updating question: M-x package-list-packages -> this will take you to a list of all your installed packages. It should also update the list. Then you can type the letter "u" to signal you want to update all packages that are tagged as out of date. And then you follow that with "x" to eXecute the command. And you should see a bunch of messages scrolling by. This can take a while if you have a lot of out of date packages. 

To figure out why python can't find your executable first make sure you have one. Test that in the terminal. You can try typing python or python3 to find the one that starts an interpreter (which you can then quit with `quit()`). Then you can try `which python` or `which python3` depending on the one that worked to see the executable path. If you do see an executable path you can do ~C-h v elpy-rpc-python`~ to learn how to manually set it, but you shouldn't have to. Sounds like something else is non-standard.

**Comment by brittAnderson** [comment]
I see that you closed the issue. Did you get it fixed. If so, please post the fix for others than you can close.

**Comment by hduqeh** [comment]
Oops. Thank you for the reminder Dr. Anderson.
When I try to update packages, I tried typing the letter 'u' then 'x' to execute the command but it still did not work.
However, I was able to solve the issue 'elp-rpc-python' by placing it into my init file and it got everything working for me again.



Sent from my Bell Samsung device over Canada's largest network.

________________________________
