### ISSUE TITLE
Emacs Python Issue 

### ISSUE THREAD

**Issue by isimione** [brittAnderson/psych363Practice#124]
When trying to carry out a python code in Emacs (e.g., Ctrl C, Ctrl C) I get this message: Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python3" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally.

**Comment by brittAnderson** [comment]
happy to answer this here, but better to make future issues in the course [repo]( https://github.com/brittAnderson/Intro2Computing4Psychology ). If you can evaluate python then you can ignore that error message. One way to test is to run M-x run-python. If you see a python interpreter pop open in emacs, then things should work and you can ignore the message. If not, then we want to fix that first. 

I think if you add the following code to your init file it will suppress the warning, but I haven't tested. Add to this issue to let me know what happens.

    (setq python-shell-completion-native-disabled-interpreters '("python3"))

**Comment by isimione** [comment]
I was able to open my python interpreter in emacs previously but I was still unable to produce an output (kept saying something like code evaluation was blocked?). I did add the code you suggested to my init file and was able to produce output though! Thank you!

**Comment by steve-the-bayesian** [comment]
I can evaluate python code, and I'd like to ignore the error message.  But every time I start a python shell the warning message pops open a new frame, which I have to go close if I want to ignore it.  What's the best way to keep the warning frame from opening?

**Comment by brittAnderson** [comment]
Try adding this to your init file and then restart emacs. 
`(setq python-shell-completion-native-enable nil)`

And also avoid using "tab" in python files. Just use a fixed number of spaces when you indent. 

Let me know if that fixes it.

**Comment by steve-the-bayesian** [comment]
Thank you Britt!  That did the trick.
