### ISSUE TITLE
Sarah - Persistence Issue Mac 

### ISSUE THREAD

**Issue by s3naseem** [brittAnderson/psych363Practice#4]
I have installed Xubuntu onto a new 64Gb USB and have gotten to reboot my Mac laptop through it. I am stuck at testing for persistence, once I save a text file to desktop and relaunch Xubuntu, it starts as a new with no previous changes saved. I am not sure where I went wrong. 

update: just realized I used Etcher and it doesn't support persistence! Will be trying again with UNetbootin.

**Comment by skundurt** [comment]
I used UNetbootin and I'm having the same issue!
