### ISSUE TITLE
Question: How do we zoom in on a PDF in emacs?

### ISSUE THREAD

**Issue by s3naseem** [brittAnderson/psych363Practice#64]
I generated a pdf for my res report assignment but the display for it on emacs is very small. In Dr. Anderson's Vimeo video, he was able to zoom in on the pdf but did not show his keys on how to do that. I tried googling it but all that comes up is how to zoom the text font instead which does not work for me with my PDF. Any help would be really appreciated.

**Comment by brittAnderson** [comment]
oops. Sorry I didn't see this before. If you are viewing with the default doc-viewer it is the + and - key that enlarge.It is the same if you are using pdftools (which is what I was using).
